name: Build
on:
  push:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"

# Allow only a single workflow running on the same PR or branch
concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyOpenGL PySide2
      - name: git clone
        shell: bash
        run: |
          git clone https://github.com/tamaskenez/OpenUSD.git --depth=1 --branch=relocatable_config_with_tbb_opensubdiv
      - name: Build USD
        run: |
          REM Unset BOOST_ROOT on Windows. The VS2017-Win2016 image
          REM sets this env var to a pre-installed boost which causes
          REM the USD build to favor this over the boost built by
          REM build_usd.py. This causes the build to fail, because
          REM the pre-installed boost does not include boost_python27
          call set BOOST_ROOT=
          cd OpenUSD
          python build_scripts/build_usd.py --no-materialx --generator "Visual Studio 16 2019" --build USDgen/build --src USDgen/src USDinst --build-args USD,"-DPXR_ENABLE_PRECOMPILED_HEADERS=OFF" -v --onetbb
        shell: cmd          
